"""init

Revision ID: 2faf9f151ed8
Revises:
Create Date: 2025-01-14 19:01:46.079826

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2faf9f151ed8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Content",
        sa.Column("session_uuid", sa.String(length=36), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("white_page_url", sa.String(), nullable=True),
        sa.Column("black_page_url", sa.String(), nullable=True),
        sa.Column("text_ad", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("session_uuid"),
    )
    op.create_index(op.f("ix_Content_domain"), "Content", ["domain"], unique=False)
    op.create_index(op.f("ix_Content_ip"), "Content", ["ip"], unique=False)
    op.create_index(op.f("ix_Content_session_uuid"), "Content", ["session_uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Content_session_uuid"), table_name="Content")
    op.drop_index(op.f("ix_Content_ip"), table_name="Content")
    op.drop_index(op.f("ix_Content_domain"), table_name="Content")
    op.drop_table("Content")
    # ### end Alembic commands ###
